const db = require('./connection');
const { Body, Food, User} = require('../models');

db.once('open', async () => {
    await Body.deleteMany();

    const BodyDocs = await Body.insertMany([
        { plan: 'Cutting', foods:[] },
        { plan: 'Bulking', foods:[] },
      ]);    

console.log(' body seeded');

await Food.deleteMany();

const FoodDocs = await Food.insertMany()([
    {
        name: "Orange Chicken",
        category: "asian",
        image: "",
        calories: "242kcal",
        fats: "8g",
        carbs: "10g",
        protein: "32g",
    },
    {
        name: "Orange Chicken",
        category: "asian",
        image: "",
        calories: "637kcal",
        fats: "29g",
        carbs: "43g",
        protein: "50g",
    },
    {
        name: "Fried rice",
        category: "asian",
        image: "",
        calories: "432kcal",
        fats: "13g",
        carbs: "43g",
        protein: "35g",
    },
    {
        name: "Fried rice",
        category: "asian",
        image: "",
        calories: "523cal",
        fats: "13g",
        carbs: "35g",
        protein: "62g",
    },
    {
        name: "Dumplings",
        category: "asian",
        image: "",
        calories: "243cal",
        fats: "2.8g",
        carbs: "32g",
        protein: "17g",
    },
    {
        name: "Dumplings",
        category: "asian",
        image: "",
        calories: "447cal",
        fats: "20g",
        carbs: "35g",
        protein: "28g",
    },
    {
        name: "Egg rolls",
        category: "asian",
        image: "",
        calories: "142",
        fats: "3.5g",
        carbs: "18.6g",
        protein: "9g",
    },
    {
        name: "Lumpia",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Curry?",
        category: "asian",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Curry?",
        category: "asian",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Chilaquiles",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Chilaquiles",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Enchiladas",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Enchiladas",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Taco",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Taco",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Ceviche",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Ceviche",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Torta",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Torta",
        category: "Mexican",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Hamburger",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Hamburger",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Philly Cheese",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Philly Cheese",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Jambalaya",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Jambalaya",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Fried Chicken",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Fried Chicken",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Mac&Cheese",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Mac&Cheese",
        category: "American",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Milk Tea Boba",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Milk Tea Boba",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Flan",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Flan",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Cookies",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Cookies",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Apple Pie",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "American Pie",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Halo Halo",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
    {
        name: "Halo Halo",
        category: "",
        image: "",
        calories: "",
        fats: "",
        carbs: "",
        protein: "",
    },
]);
console.log("foods seeded");

await User.deleteMany();

await User.create({
    firstName: "Lifting",
    lastName: "Larry",
    email: "liftinglarry@Marco.com",
});

await User.create({
    firstName: "",
    lastName: "",
    email: "",
});


console.log("user seeded")

process.exit();

})